services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: barsdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    env_file: .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
